name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
      - name: Upload pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chmod +x ./push.sh;./push.sh
